services:

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      retries: 10

  backend:
    image: jarodkonijnenberg/financial-app:latest
    container_name: financial-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
    depends_on:
      - backend
    ports:
      - "4200:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://frontend:80"]
      interval: 5s
      timeout: 3s
      retries: 20

  e2e:
    image: cypress/included:13.6.0
    working_dir: /e2e
    volumes:
      - ./:/e2e
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://frontend:80
